language: objective-c
sudo: false

matrix:
  include:
    - osx_image: xcode11
      env: TRAVIS_NODE_VERSION=10
    - osx_image: xcode11
      env: TRAVIS_NODE_VERSION=12

before_install:
  - nvm install $TRAVIS_NODE_VERSION

install:
  - npm install
  - npm install ios-deploy
  - npm install -g codecov

script:
  - node --version
  - npm --version
  - npm run lint
  - npm run unit-tests
  - npm run test:component
  - npm run e2e-tests
  - npm run objc-tests
  - npm run cover

after_script:
  - codecov
