language: objective-c
osx_image: xcode9.3
sudo: false

env:
  matrix:
    - TRAVIS_NODE_VERSION: '6'
    - TRAVIS_NODE_VERSION: '8'
    - TRAVIS_NODE_VERSION: '10'

before_install:
  - nvm install $TRAVIS_NODE_VERSION

install:
  - npm install
  - npm install ios-deploy
  - npm install -g codecov

script:
  - node --version
  - npm --version
  - npm run eslint
  - npm run unit-tests
  - npm run test:component
  - npm run e2e-tests
  - open -b com.apple.iphonesimulator
  - npm run objc-tests
  - npm run cover

after_script:
  - codecov
