language: objective-c
sudo: false

matrix:
  include:
    # Run one test with Xcode 9.x, the rest with 10.1
    - osx_image: xcode9.3
      env: TRAVIS_NODE_VERSION=10
    - osx_image: xcode10.1
      env: TRAVIS_NODE_VERSION=6
    - osx_image: xcode10.1
      env: TRAVIS_NODE_VERSION=8
    - osx_image: xcode10.1
      env: TRAVIS_NODE_VERSION=10

before_install:
  - nvm install $TRAVIS_NODE_VERSION

install:
  - npm install
  - npm install ios-deploy
  - npm install -g codecov

script:
  - node --version
  - npm --version
  - npm run eslint
  - npm run unit-tests
  - npm run test:component
  - npm run e2e-tests
  - npm run objc-tests
  - npm run cover

after_script:
  - codecov
