language: objective-c
osx_image: xcode8.3
sudo: false
env:
  matrix:
  - TRAVIS_NODE_VERSION: '4.2'
  - TRAVIS_NODE_VERSION: '6.11'
before_install:
- npm cache clean -f
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
- node --version
install:
- npm install
- npm install ios-deploy
- npm install -g codecov
script:
    - npm run unit-tests
    - npm run e2e-tests
    - open -b com.apple.iphonesimulator    
    - npm run objc-tests
    - npm run cover
    - npm run eslint
after_script: codecov
