environment:
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  # Lines below required due to uncrustify installation failure on Windows
  - npm install --prod
  - npm install jshint jasmine rewire

build: off

test_script:
  - node --version
  - npm --version
  - npm run jshint
  - npm run unit-tests
