# #####################################################################
# Automatically generated by qmake (2.01a) Tue Nov 3 16:03:38 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += webkit
HEADERS += basecommand.h \
    commandmanager.h
