# #####################################################################
# Automatically generated by qmake (2.01a) Tue Nov 3 16:03:38 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    deviceinfo.cpp \
    webview.cpp \
    debug.cpp
QT += webkit
HEADERS += commandmanager.h \
    deviceinfo.h \
    webview.h \
    utils.h \
    debug.h
OTHER_FILES += index.html
