# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Lint

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - '*'

jobs:
  lint-editorconfig:
    name: Editor Linting
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: editorconfig-checker/action-editorconfig-checker@4b6cd6190d435e7e084fb35e36a096e98506f7b9
      - run: editorconfig-checker

  lint-js:
    name: JavaScript Linting
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Run npm install
        run: npm ci
        env:
          CI: true

      - name: Run linter
        run: npm run lint:js
        env:
          CI: true

  lint-markdown:
    name: Markdown Linting
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101
        with:
          globs: |
            **/*.md
            !**/node_modules
            !**/.git

  lint-objc:
    name: Objective-C Linting
    runs-on: macos-26

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Run linter
        run: npm run lint:objc
        env:
          CI: true

  lint-swift:
    name: Swift Linting
    runs-on: macos-26

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Run linter
        run: |
          swiftformat --lint --strict --verbose ./CordovaLib
          swiftformat --lint --strict --verbose ./templates/project
